### ISSUE TITLE
No button to show image drawer when ComfyUI's new menu beta is enabled.

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#10]
Simple enough issue.  The button to show the image drawer after it's been hidden only exists in the old menu, not the new one.  As a result, you have to disable the new menu in ComfyUI's settings to show the image drawer again.

**Comment by JaredTherriault** [comment]
Hey thanks for letting me know about the new UI, i had no idea this was a thing. I've gone ahead and implemented this for you, give it a try. Keep in mind the button will initialize its position on refresh only, so if you switch from old to new interface, you won't see the button until you refresh the page.

In the future I won't be doing very much for the new interface until it gets out of beta, just enough to make sure it doesn't malfunction. When it is production ready I will focus more on it, but minor UI issues (as in more minor than this) won't be addressed. For example, how the drawer covers the menu when both it and the menu are top anchored or bottom anchored, or when the drawer has a height of 100 since those things can be worked around on the end user's side for now.

**Comment by Monty1836** [comment]
I agree, no point fixing minor issues until it's out of beta.  Just tested it out, looks like a refresh is only needed when you enable, or disable the beta menu.  The button switches to top or bottom just fine. I actually had the button displaying properly on both menus on one test, and I have no idea what I did to cause that, but it only lasted until a refresh.

I actually only noticed the issue because I saw the beta menu in the settings screen, and wanted to see what it was.  I'm not even planning to use the new menu yet, because multiline text boxes are rendering in the wrong position with it enabled, but I figured I should submit the issue to make sure that your feed doesn't break if they push it as the default in the future.
