### ISSUE TITLE
Feature Request: Favorite Images

### ISSUE THREAD

**Issue by Monty1836** [JaredTherriault/ComfyUI-JNodes#12]
Something I've always wanted in ComfyUI, but I couldn't find a way to do, is to save particular images that I want to keep into their own folder.  The best solution I've found is to just drag images, previously from the custom-scripts image feed, which I've now replaced with your image drawer, into the folder to save them there.

I would be thrilled if you could add a new folder to the image drawer for favorites, and a button to quickly, and easily copy images from the other folders into it.

**Comment by JaredTherriault** [comment]
This is on the backburner and something I'd like to do, along with a "saved prompts" folder where you can peruse images that you like that follow a certain prompt, but it's a matter of time. I'll move this up the priorities list but no promises on a delivery date.

To speed things up, can you give me an idea of the workflow you'd like? Part of the implementation is design, so if you can help me design it the delivery will be much faster. Any visual references to existing similar workflows in other applications would also be appreciated!

**Comment by Monty1836** [comment]
Being on the backburner is alright, there's no rush!  For favorite images, I was thinking of just adding it to the context menu, either before, or after the "Show in File Manager" button.  When you click the button, the image would just get copied into a favorites folder.
![Mockup](https://github.com/user-attachments/assets/97dc23f4-22de-4b30-b1e7-8a72860e6b51)

Along with also having a new Favorites context available in the selector, so you can view favorited using the image drawer.
![Mockup2](https://github.com/user-attachments/assets/f0d69fb2-56c2-420b-a0e9-0c3e983fa261)

Another option for adding things to favorites is an icon like you have for the models context type, but I don't know if the subdirectory context type currently supports them, given it has a checkbox instead.

If you can add icons to the subdirectory context type, that would also be a good way to quickly retrieve prompts.  They could work just like the ones that models have, being able to either click the button to copy, or drag the button for the positive, and negative prompts into a text field.  Just click the heart to add it to your favorites, and later when you want to generate more images with that prompt, just open favorites, and drag the buttons into your prompt nodes if you don't want to load the whole workflow.
![Mockup3](https://github.com/user-attachments/assets/b0d32487-a814-40d4-9d0f-597b1dc8dc52)

**Comment by JaredTherriault** [comment]
Damn, look at you with mockups and everything. This is _greatly_ appreciated, thank you!

Personally I'm not a fan of creating yet even more subdirectories inside the Comfy folder, but I see no issue with creating subdirectories inside an existing comfy one, like output perhaps. Or maybe not even a separate folder where we copy images, but rather have a lookup table saved to the config where an image is 'marked' as a favourite and the Favorites context just recalls all images from the table, leaving them in their original directories. Though that can get hairy if the images are moved which is not unreasonable for the end user to do.

The reason I'm trepidatious about copying is for disk space concerns, especially with animatediff where outputs can get rather large. What's your take?

**Comment by JaredTherriault** [comment]
Thank you for getting back to me on this. Funny thing, I actually decided to tackle this yesterday and we had pretty much all the same ideas here, haha. I also like the idea of a list, but I fear how crowded the overflow menu on images will become, so for now we'll just do a single Favourites folder, configurable in Settings. Perhaps in the future I can implement a secondary flyout for the overflow menu or something like that but I don't want to add too much nesting, I'll have to think about it more. 

Nonetheless something like this is now pushed along with a batch favourites button when you select multiple images. Check it out!

**Comment by Monty1836** [comment]
Just tested it out, looks to me like you haven't gotten to making the favorites folder appear in the feed.  More importantly though, the folder path is relative to the execution directory, not the ComfyUI folder.  Very easy to work around, but it did take me a moment to track down where exactly it copied the files to.  In my case, that means it's actually just one folder up from the actual ComfyUI folder.  On other systems though, it could be anywhere, depending on where the user launches ComfyUI from.

**Comment by JaredTherriault** [comment]
Hey, thanks for the reminder and head sup. Just forgot to resolve the destination path, but that's in there now. Favourites Context is also added. It will automatically pick up the new Favourites directory when you change it, but you will need to click Refresh in the Favourites context to see the change. I played with the idea of refreshing the context automatically when the directory setting changes, but if a person has a ton of favourites that's just asking for a crash since it would update on every keystroke.

**Comment by Monty1836** [comment]
Testing it out, I had a little trouble with the favorites context not updating at first, and I'm not sure why.  Maybe because I have two ComfyUI tabs open?  It was fixed after I used the copy to favorites button once, and I can't seem to reproduce it.

If you still want to refresh the favorites context automatically, you could potentially do something like starting a small timer when the value is changed before the setting actually saves, and refreshing that timer whenever a new change is detected so that it only saves when the user stops typing.

Now two things.  First, entering the name of one of the other contexts will show that context instead of the literal directory.  So because my output folder is actually set to the temp folder because I only want to save things manually, if I try to set the favorites folder to the actual folder named "output" it redirects it to the temp folder.  Fortunately, I don't actually want to use that folder, but I tested it to see what would happen anyway. Second, would it be possible to make it so that when you push the copy to favorites button, it also refreshes the favorites context either immediately, or next time you open it?  Currently you manually refresh after adding something to the folder, even if you did it through the image drawer itself.

**Comment by JaredTherriault** [comment]
Okay, so your first issue seems pretty edge-cased. Resolving a local directory pretty much requires asking comfy where the directory is first otherwise people who use directories external to the comfy directory lose all functionality of the drawer. In this case, it's best to set up symbolic links or simply put in an absolute path like 'C:/comfy/favourites' on Windows or '/run/media/storage/comfy/favourites' on Unix.

For the second issue, that is possible, but maybe not desired. When testing the drawer with huge directories, any kind of auto-refresh was uncomfortable since I would want to hop back and forth between contexts and if they refresh on change, it can be a real pace-breaker. This isn't an issue for very small directories, but I want the experience to be consistent. It doesn't make sense to implement this for small directories only, because then the person who gets used to that builds up the directory over time and starts wondering why it doesn't update and opens an issue. Additionally, how do I decide what is and isn't a 'small directory'? For people with fast computers this can be in the 1000s, for people using a Collab it can be low 100s. I could make this magic number configurable, but then we're relying on end users to make guesswork, especially since video- and image-centric directories will have different resource requirements. 

Now what we could do is make it an option to auto-refresh contexts on switch that defaults to off for advanced users who would prefer that, but even then sometimes you want it to auto refresh for some contexts and other times you don't. I wouldn't mind auto-refresh for Temp but I'd hate it for Lora/lycoris (since I have over 1k loras). We could make it happen on a per-context basis but now we're really over-parameterizing and JNodes settings is kinda crowded as it is :p 

I don't mean to come across as negative here, I just see several other possible issues that could arise from trying to solve these issues and I'd really prefer to keep new github issue submissions at a minimum.

**Comment by Monty1836** [comment]
Sorry, sounds like there's some misunderstanding as to what I meant.  For the auto-refreshing, I'd been referring to what you'd mentioned previously, to refresh the context when you change the directory in the settings.  A timer solves the issue of having the context refresh on every keypress, since every keypress would refresh the timer to delay actually saving the setting, if it's viable to implement in ComfyUI extensions.  I actually don't think it's an issue that's important to resolve, since refreshing when you change the directory is a pretty minimal inconvenience.  I don't think people will be changing the directory very often.

For refreshing the favorites context on changes, I was just thinking to refresh the favorites, ideally in the background, but on next load is also acceptable, only when you push the "copy to favorites" button.  I do agree having it be toggleable in settings would be a good idea, though.

I don't think other contexts should auto refresh, given that most won't change a lot, and the one that does, the temp folder, is normally the same content as the feed, and if it's not cleared out often, it can get extremely large.

As for resolving directories, I'm not bothered by that, I just mention it because it might be unexpected behaviour for someone in the future.  I think it's better to bring it to attention than to never mention it, since knowing about it could potentially save you some trouble down the line if you get a report about it without much information as to what's going on.

Don't worry about coming off as negative, you seem to be a perfectly reasonable person, and I'd rather have in-depth discussion than sugar coating!

**Comment by Monty1836** [comment]
I'm going to close this issue, since the functionality has already been added, and I don't  think there's any reason to have it cluttering things.  If you disagree, feel free to re-open it.  It functions as I wanted it, and I've been really enjoying it ever since you added it.  Thank you again for making ComfyUI so much better!
