### ISSUE TITLE
Token count always starts at 80?

### ISSUE THREAD

**Issue by raphaelgrau** [JaredTherriault/ComfyUI-JNodes#14]
Hey, I'm trying to use your Token Counter node but even when the prompt is empty it starts at 80/154 token.

See in the screenshot below : 

![Screenshot 2024-08-03 111938](https://github.com/user-attachments/assets/e67f2503-da6d-4bef-8d2c-6981deb789ab)

Is it normal? Thanks!

**Comment by JaredTherriault** [comment]
Yikes, thanks for this - this node needed some love. I hadn't noticed it was broken for SDXL since I was still using SD1.5 haha. I've pushed an update that should solve this for at least SDXL, but I don't have any more time today to look into SDXL 2 or 3 or Flux. If you have time, please check it out and close the issue if it works for you. Thanks!

**Comment by raphaelgrau** [comment]
Thanks for fixing this! I'll close the issue

![Screenshot 2024-08-04 093213](https://github.com/user-attachments/assets/293bde69-9c41-4e7b-9c37-3bd96cf26cc3)
